#!/bin/bash
PROJECT=stealth

# When recreating to repair lintian/linda messages, define REPAIR
# and rerun `distribution'
# REPAIR=YES

[ -d ${PROJECT} ] || exit 1             # the $PROJECT dir must exist

cvsremove

cd  ${PROJECT}
[ -s VERSION ] || exit 1                # VERSION must exist in $PROJECT


if [ "$REPAIR" == "" ] 
then
    build distclean
fi

export STEALTH=minimal 


. VERSION                               # load it
DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

cd ..                                   # change the CVS dir name to the
mv ${PROJECT} ${DISTRIBUTION}           # distribution's dir name

if [ "$REPAIR" == "" ] 
then
    rm -f ${PROJECT}_${VERSION}-*       # remove old files if existing
                                        # create the .orig source tar
    tar czvf ${PROJECT}_${VERSION}.orig.tar.gz --exclude=debian ${DISTRIBUTION}
fi

cd ${DISTRIBUTION}                      # now build the distribution
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..                                   # change the distribution's dir name
mv ${DISTRIBUTION} ${PROJECT}           # back to the cvs's dir name

cvsrestore

echo LINTIAN ...
lintian -i ${PROJECT}_${VERSION}*.changes 

echo LINDA ...
linda   -i ${PROJECT}_${VERSION}*.changes
