#!/bin/sh
PROJECT=stealth

cvsremove

cd stealth

make/clean
make/man
make/manual

export STEALTH=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

