#!/bin/sh
PROJECT=stealth

cvsremove

cd stealth

# When recreating to repair lintian/linda messages, uncomment the following
# three commands and rerun `distribution'
make/clean
make/man
make/manual

export STEALTH=minimal 
dpkg-buildpackage -mf.b.brokken@rug.nl  -rfakeroot 2>&1 | tee /tmp/$PROJECT 

cd ..

cvsrestore

echo LINTIAN ...
lintian -i *.changes 
echo LINDA ...
linda   -i *.changes
