#!/bin/bash
PROJECT=stealth

# manual()
# {
#     echo "
# Due to some problem with the latest Debian pdf-construction the manual
# is preconstructed here and the distribution will simply contain the
# manual in its ready-to-run form. The Debian control files are modified
# accordingly.
# This state should be lifted once Debian's problems are solved.
# "
#     pause
#     cd stealth
#         build distclean
#         build manual-tmp
#         rm -rf documentation/manual
#         rm tmp/manual/LaTeX/*.{aux,dvi,log,toc}
#         mv tmp/manual documentation
#         build distclean
#     cd ..
#     pause
# }

if [ -e /usr/share/common-licenses/GPL ] ; then
    cp /usr/share/common-licenses/GPL ${PROJECT}/LICENSE
fi

                                        # load the version
VERSION=`grep VERSION ${PROJECT}/VERSION |
    sed 's/#define[[:space:]]\+VERSION[[:space:]]\+"\(.*\)"/\1/'`

DISTRIBUTION=${PROJECT}-${VERSION}      # define the distribution's dir name

tgz()
{
    ln -s ${PROJECT} ${DISTRIBUTION}        # distribution's dir name
    tar czvf $1 --exclude-from=excluded  ${DISTRIBUTION}/*
    rm -f ${DISTRIBUTION} ${PROJECT}/LICENSE  # rm the link/LICENSE file
}

case "$1" in 
    (d)
        tgz ${HOME}/debian/${PROJECT}/tarballs/${PROJECT}_${VERSION}.orig.tar.gz
    ;;

    (t|u)
        tgz ${PROJECT}_${VERSION}.tar.gz

        if [ "$1" == "u" ]
        then
            scp ${PROJECT}_${VERSION}.tar.gz oosix:ftp/debian/${PROJECT}
            md5sum ${PROJECT}_${VERSION}.tar.gz
        fi
    ;;

    (*)
        echo "
Provide arg:
    d (debian)  to create a local .orig.tar.gz archive in 
                ../debian/${PROJECT}/tarballs
    l (local)   to create ${PROJECT}_${VERSION}.tar.gz in this directory
    u (upload)  same as 't', but upload to oosix and show MD5 hash
"
    exit 1
    ;;

esac



