#!/bin/sh

yodl2html index.yo

scp ../stealth/tmp/manual/html/stealth*.html ../stealth/tmp/manhtml/*.html \
    index.html stealth.jpg \
    fbb@shell.sourceforge.net:/home/groups/s/st/stealth/htdocs/
