#!/bin/sh

FLAG="-O3"
#FLAG=-DDEBUG

COMPILER=g++
HASHNAMESPACE=__gnu_cxx

run()
{
    echo $*
    $*
    if [ "$?" != "0" ] ; then 
        echo Non-zero return value
        exit 1
    fi
}

rm -f libstealth.a

sh VERSION.sh

NR=1
for x in util configsorter reporter scanner iofork monitor
do
    run cd $x
    for c in *.cc
    do
        run $COMPILER -c -Wall $FLAG $c
    done
    for o in *.o
    do
        run mv $o $NR$o
    done
    run ar rsv ../libstealth.a *.o
    run rm *.o
    run cd ..

    let NR=$NR+1
done

run $COMPILER -o stealth -Wall  $FLAG stealth.cc -lstealth -lbobcat -L.
run strip stealth




