#!/bin/sh

# Argument 1: optional prefix path to installation paths, e.g., debian/debian

PREFIX=$1
[ "$PREFIX" == "" ] && PREFIX=/

. INSTALL.cf
. make/parameters
. make/substitutions
. make/scripts

echo "  install the executable"
req mkdir -p $1$BIN
req cp tmp/bin/* $1$BIN

echo "  install the manual page stealth.1"
req mkdir -p $1$MAN
reqeval "gzip -9 < tmp/man/stealth.1 > $1$MAN/stealth.1.gz"

echo "  install the manual page stealthman.html"
req mkdir -p $1$DOC/man $1$DOC/scripts 
req cp tmp/manhtml/stealthman.html $1$DOC/man

echo "  install the information directly in and under $DOC"
reqzip ${PREFIX} README ACKNOWLEDGEMENTS debian/changelog

echo "  install scripts"
req cp  stealthmail $1$DOC/scripts

echo "  install examples"
req cp -r example-policies $1$DOC

echo "  install manual"
req cp -r tmp/manual $1$DOC
    




