#!/bin/sh

. make/parameters
. make/substitutions
. make/scripts

make/special

NR=0
for x in `cat CLASSES`
do
    req cd $x
    SRC=`find ./  -maxdepth 1 -regex '.*\.cc' -printf "%f\n"`
    [ "$SRC" == "" ] && (cd ..; continue)
    mkdir -p o
    for src in $SRC
    do
        BASE=${src%\.[^\.]*}
        OBJ=o/${NR}${BASE}.o
        [ -e $OBJ -a $src -nt $OBJ  -o \
          ! -e $OBJ -a \
            \( ! -e ../$LIBRARY -o $src -nt ../$LIBRARY \) ] &&
                             req $GCC $COPTS -o  $OBJ -c ${src}
    done
    cd ..
    let NR=${NR}+1
done

echo compiling additional sources
for src in *.cc
do
    [ "$src" == "$MAIN" ] && continue
    mkdir -p o
    BASE=${src%\.[^\.]*}
    OBJ=o/${BASE}.o
    [ -e $OBJ -a $src -nt $OBJ  -o \
                ! -e $OBJ -a \( ! -e $LIBRARY -o $src -nt $LIBRARY \) ] &&
        req $GCC $COPTS -o  $OBJ -c $src
done

BASE=${MAIN%\.[^\.]*}
MAINOBJ=${BASE}.o

OBJ=`find ./ -regex '.*\.o' -and -not -name $MAINOBJ -print`

if [ "$OBJ" != "" ] 
then
    echo ar rs $LIBRARY '*/o/*.o'
    ar rs $LIBRARY $OBJ || exit 1
    req rm $OBJ
fi
