#!/bin/sh

. INSTALL.cf
. make/scripts

make/special

mkdir -p tmp/man tmp/manhtml

MANPAGE=../tmp/man/stealth.1
MANHTML=../tmp/manhtml/stealthman.html

req cd manpage

if [ ! -e $MANPAGE -o stealth.yo -nt $MANPAGE -o \
    ../release.yo -nt $MANPAGE ] 
then
    req yodl2html -o $MANHTML stealth
    req yodl2man -o $MANPAGE stealth
fi
