#!/bin/sh

. make/parameters
. make/substitutions
. make/scripts

mkdir -p tmp/bin tmp/o

req make/library

BASE=${MAIN%\.[^\.]*}
OBJ=tmp/o/${BASE}.o

[ ! -e $OBJ -o $MAIN -nt $OBJ ] && req $GCC $COPTS -o $OBJ -c $MAIN

req $GCC -o tmp/bin/$EXECUTABLE $OBJ $LOPTS
