#!/bin/sh

. INSTALL.cf
. make/parameters
. make/substitutions
. make/scripts

mkdir -p tmp/bin tmp/o

make/library

BASE=${MAIN%\.[^\.]*}
OBJ=tmp/o/${BASE}.o

[ ! -e $OBJ -o $MAIN -nt $OBJ ] && req g++ $COPTS -o $OBJ -c $MAIN

req g++ -o tmp/bin/$EXECUTABLE $OBJ $LOPTS
