#!/bin/sh

. VERSION

# . INSTALL.cf
# . make/parameters
# . make/substutions
# . make/scripts


if [ ! -e release.yo -o VERSION -nt release.yo ] 
then
    echo "
SUBST(_CurVers_)($VERSION)
SUBST(_CurYrs_)($YEARS)
" > release.yo

echo "
#define _CurVers_ \"$VERSION\"
#define _CurYrs_ \"$YEARS\"
" > release.h

fi



